# migrations/ フォルダ全体の役割
# モデルの追加・変更をデータベースに反映するための**指示書（履歴）**です。
# makemigrations コマンドで生成され、migrate コマンドで実行されます。
# 各ファイルは1つのバージョン変更を表しています。

# Generated by Django 5.1.1 on 2024-09-26 06:16
# Page モデルの初期作成（団員の基本情報）

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('kyogleeid', models.IntegerField(max_length=10, verbose_name='団員ID')),
                ('affiliation', models.CharField(max_length=100, verbose_name='所属')),
                ('part', models.CharField(max_length=100, verbose_name='パート')),
                ('role', models.CharField(max_length=100, verbose_name='役職')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
