# Generated by Django 5.1.1 on 2024-09-26 13:21
# kyogleeid フィールドの型修正（max_length削除）
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='kyogleeid',
            field=models.IntegerField(verbose_name='団員ID'),
        ),
    ]
