# Generated by Django 5.1.1 on 2024-09-26 14:41
# Page モデルに新しいフィールド picture（画像） を追加
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_page_kyogleeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='member/picture/', verbose_name='写真'),
        ),
    ]
