# Generated by Django 5.1.1 on 2024-09-27 09:34
# 入団年 joinyear を追加
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_page_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='joinyear',
            field=models.IntegerField(default=2023, verbose_name='入団年'),
        ),
    ]
