# Generated by Django 5.1.1 on 2024-09-27 13:22
# 出欠・練習日管理用の Member / Practice / Attendance モデル追加
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_page_joinyear'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('members', models.ManyToManyField(through='member.Attendance', to='member.member')),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='practice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.practice'),
        ),
    ]
