# Generated by Django 5.1.1 on 2025-05-16 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_attendance_practice_attendance_practice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practice',
            name='members',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
    ]
