# Generated by Django 5.1.1 on 2025-05-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_page_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='part',
            field=models.CharField(choices=[('top', 'トップ'), ('second', 'セカンド'), ('baritone', 'バリトン'), ('bass', 'ベース')], max_length=10, verbose_name='パート'),
        ),
    ]
