# Generated by Django 5.1.1 on 2025-05-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_alter_page_part'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='affiliation',
            new_name='faculty',
        ),
        migrations.AlterField(
            model_name='page',
            name='joinyear',
            field=models.IntegerField(verbose_name='入団年'),
        ),
    ]
