# Generated by Django 5.1.1 on 2025-05-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_rename_affiliation_page_faculty_alter_page_joinyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='role',
            field=models.CharField(choices=[('Kanjichou', '幹事長'), ('Gaimu', '外務'), ('Naimu', '内務'), ('Zaimu', '財務'), ('Shikisha', '指揮者'), ('Fukushikisha', '副指揮者')], max_length=20, verbose_name='役職'),
        ),
    ]
