# Generated by Django 5.1.1 on 2025-05-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_alter_page_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='page',
            name='role',
        ),
        migrations.AddField(
            model_name='page',
            name='role',
            field=models.ManyToManyField(blank=True, to='member.role', verbose_name='役職'),
        ),
    ]
