# Generated by Django 5.1.1 on 2025-05-17 22:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_role_remove_page_role_page_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='role',
        ),
        migrations.RemoveField(
            model_name='page',
            name='user',
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名前')),
                ('kyogleeid', models.IntegerField(verbose_name='期')),
                ('joinyear', models.IntegerField(verbose_name='入団年')),
                ('faculty', models.CharField(max_length=100, verbose_name='所属')),
                ('part', models.CharField(choices=[('top', 'トップ'), ('second', 'セカンド'), ('baritone', 'バリトン'), ('bass', 'ベース')], max_length=10, verbose_name='パート')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='member/picture/', verbose_name='写真')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('role', models.ManyToManyField(blank=True, to='member.role', verbose_name='役職')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
