# Generated by Django 5.1.1 on 2025-05-17 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_expenseapplication_applicant'),
        ('member', '0012_remove_page_role_remove_page_user_member'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
    ]
