# Generated by Django 5.1.1 on 2025-06-08 02:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_delete_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='画像'),
        ),
    ]
