# Generated by Django 5.1.1 on 2025-05-24 08:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0013_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(default=datetime.time(18, 30))),
                ('end_time', models.TimeField(default=datetime.time(21, 0))),
                ('status', models.CharField(choices=[('practice', '練習'), ('teacher_practice', '先生練習'), ('concert', '演奏会'), ('welcome', '新歓'), ('none', 'なし')], default='none', max_length=20)),
                ('location', models.CharField(choices=[('地塩寮', '地塩寮'), ('２階共用室', '２階共用室'), ('地下共用室', '地下共用室'), ('4共21', '4共21'), ('4共30', '4共30'), ('その他', 'その他')], default='その他', max_length=100)),
                ('custom_location', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('teachers', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', '出席'), ('late', '途中参加'), ('absent', '欠席'), ('undecided', '未定')], default='undecided', max_length=10)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='practice_management.practiceday')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('members', models.ManyToManyField(to='member.member')),
            ],
        ),
    ]
