# Generated by Django 5.1.1 on 2025-05-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_delete_page'),
        ('practice_management', '0002_practiceday_month'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='practiceattendance',
            unique_together={('day', 'member')},
        ),
    ]
