# Generated by Django 5.1.1 on 2025-05-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_management', '0004_alter_practiceattendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceday',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
