# Generated by Django 5.1.1 on 2025-06-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice_management', '0005_practiceday_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practiceday',
            name='location',
            field=models.CharField(choices=[('地塩寮', '地塩寮'), ('２階共用室', '２階共用室'), ('２階和室', '２階和室'), ('地下共用室', '地下共用室'), ('4共20', '4共20'), ('4共21', '4共21'), ('4共30', '4共30'), ('4共31', '4共31'), ('4共40', '4共40'), ('BOX', 'BOX'), ('日仏会館', '日仏会館'), ('その他', 'その他'), ('-', '-')], default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='practiceday',
            name='status',
            field=models.CharField(choices=[('practice', '練習'), ('matsuoka_practice', '松岡練習'), ('motoyama_practice', '本山練習'), ('piano_practice', 'ピアノ練習'), ('concert', '演奏会'), ('welcome', '新歓'), ('training_camp', '合宿'), ('none', 'なし')], default='none', max_length=20),
        ),
    ]
