# Generated by Django 5.1.1 on 2025-06-11 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_management', '0006_alter_practiceday_location_alter_practiceday_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practiceday',
            name='teachers',
        ),
    ]
