# Generated by Django 5.1.1 on 2025-05-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_expenseapplication_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseapplication',
            name='receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/'),
        ),
    ]
