# Generated by Django 5.1.1 on 2025-05-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_alter_expenseapplication_receipt_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseapplication',
            name='status',
        ),
        migrations.AddField(
            model_name='expenseapplication',
            name='approval_status',
            field=models.CharField(choices=[('pending', '申請中'), ('refunded', '承認'), ('rejected', '却下')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='expenseapplication',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '未払い'), ('paid', '払い済み')], default='unpaid', max_length=10),
        ),
    ]
