# Generated by Django 5.1.1 on 2025-06-03 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_alter_expenseapplication_applicant'),
        ('member', '0013_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='徴収項目名')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='作成日')),
                ('deadline', models.DateField(verbose_name='徴収期限日')),
                ('default_amount', models.PositiveIntegerField(verbose_name='初期徴収額')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='徴収額')),
                ('status', models.CharField(choices=[('未', '未'), ('済', '済'), ('不要', '不要')], default='未', max_length=10, verbose_name='ステータス')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='accounting.collection')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
            options={
                'unique_together': {('collection', 'member')},
            },
        ),
    ]
