# Generated by Django 5.1.1 on 2025-06-03 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_collection_collectionrecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='collectionrecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='collection',
            name='default_amount',
        ),
        migrations.AddField(
            model_name='collection',
            name='content',
            field=models.TextField(blank=True, verbose_name='徴収内容'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(max_length=255, verbose_name='徴収項目'),
        ),
        migrations.AlterField(
            model_name='collectionrecord',
            name='status',
            field=models.CharField(choices=[('未', '未'), ('済', '済'), ('不要', '不要')], default='未', max_length=10, verbose_name='徴収ステータス'),
        ),
    ]
