# Generated by Django 5.1.1 on 2025-06-10 02:33

import cloudinary.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_alter_collectionrecord_unique_together_and_more'),
        ('member', '0014_alter_member_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(verbose_name='年度')),
                ('title', models.CharField(max_length=255, verbose_name='会計表名')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('approval_status', models.CharField(choices=[('未承認', '未承認'), ('承認済み', '承認済み')], default='未承認', max_length=20, verbose_name='予算承認ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expenseapplication',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='member.member', verbose_name='申請者'),
        ),
        migrations.AlterField(
            model_name='expenseapplication',
            name='approval_status',
            field=models.CharField(choices=[('pending', '申請中'), ('refunded', '承認'), ('rejected', '却下')], default='pending', max_length=10, verbose_name='承認ステータス'),
        ),
        migrations.AlterField(
            model_name='expenseapplication',
            name='description',
            field=models.CharField(max_length=255, verbose_name='用途・説明'),
        ),
        migrations.AlterField(
            model_name='expenseapplication',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', '未払い'), ('paid', '払い済み')], default='unpaid', max_length=10, verbose_name='支払ステータス'),
        ),
        migrations.AlterField(
            model_name='expenseapplication',
            name='receipt_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='expenseapplication',
            name='submitted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='申請日時'),
        ),
        migrations.CreateModel(
            name='CashItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('cash_type', models.CharField(choices=[('収入', '収入'), ('支出', '支出')], max_length=10, verbose_name='収支区分')),
                ('subject', models.CharField(max_length=100, verbose_name='科目')),
                ('description', models.CharField(max_length=255, verbose_name='項目')),
                ('amount', models.PositiveIntegerField(verbose_name='金額')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('cash_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounting.cashpage')),
            ],
        ),
        migrations.CreateModel(
            name='CashBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_fee', models.PositiveIntegerField(default=0, verbose_name='団員徴収')),
                ('cash_savings', models.PositiveIntegerField(default=0, verbose_name='現金／預金')),
                ('ticket', models.PositiveIntegerField(default=0, verbose_name='チケット売上')),
                ('ads', models.PositiveIntegerField(default=0, verbose_name='広告')),
                ('donation', models.PositiveIntegerField(default=0, verbose_name='寄付')),
                ('anniversary', models.PositiveIntegerField(default=0, verbose_name='50周年基金')),
                ('income_other', models.PositiveIntegerField(default=0, verbose_name='その他（収入）')),
                ('facility', models.PositiveIntegerField(default=0, verbose_name='施設／設備費')),
                ('venue', models.PositiveIntegerField(default=0, verbose_name='会館使用料')),
                ('printing', models.PositiveIntegerField(default=0, verbose_name='印刷費')),
                ('honorarium', models.PositiveIntegerField(default=0, verbose_name='御礼')),
                ('food', models.PositiveIntegerField(default=0, verbose_name='食費')),
                ('lodging', models.PositiveIntegerField(default=0, verbose_name='宿泊費')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='楽譜')),
                ('expense_other', models.PositiveIntegerField(default=0, verbose_name='その他（支出）')),
                ('misc', models.PositiveIntegerField(default=0, verbose_name='雑費')),
                ('cash_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='accounting.cashpage')),
            ],
        ),
    ]
