# Generated by Django 5.1.1 on 2025-06-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_cashpage_alter_expenseapplication_applicant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashpage',
            name='budget_balance',
            field=models.IntegerField(default=0, verbose_name='予算差額'),
        ),
        migrations.AddField(
            model_name='cashpage',
            name='expense_budget_total',
            field=models.PositiveIntegerField(default=0, verbose_name='支出予算計'),
        ),
        migrations.AddField(
            model_name='cashpage',
            name='income_budget_total',
            field=models.PositiveIntegerField(default=0, verbose_name='収入予算計'),
        ),
    ]
