# Generated by Django 5.1.1 on 2025-06-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_cashpage_budget_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashpage',
            name='budget_balance',
        ),
        migrations.RemoveField(
            model_name='cashpage',
            name='expense_budget_total',
        ),
        migrations.RemoveField(
            model_name='cashpage',
            name='income_budget_total',
        ),
        migrations.AddField(
            model_name='cashbudget',
            name='budget_balance',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='予算差額'),
        ),
    ]
