# Generated by Django 5.1.1 on 2025-06-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_remove_cashbudget_budget_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseapplication',
            name='title',
            field=models.CharField(default='無題', max_length=50, verbose_name='項目'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(default='無題', max_length=50, verbose_name='徴収項目'),
        ),
    ]
