# Generated by Django 5.1.1 on 2025-06-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_expenseapplication_title_alter_collection_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseapplication',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='経費内容詳細'),
        ),
        migrations.AlterField(
            model_name='expenseapplication',
            name='title',
            field=models.CharField(max_length=50, verbose_name='項目'),
        ),
    ]
