# Generated by Django 5.1.1 on 2025-06-11 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_alter_expenseapplication_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='徴収項目'),
        ),
        migrations.AlterField(
            model_name='expenseapplication',
            name='title',
            field=models.CharField(default='', max_length=50, verbose_name='項目'),
        ),
    ]
